#cloud-config

disable_root: true
#disable_root: false
chpasswd:
  list: |
    root:roottoor
    ebal:ping
  expire: False

ssh_pwauth: no

users:
  - name: ebal
    ssh_authorized_keys:
      - ${sshkeys}
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

write_files:
  - path: /etc/sysctl.d/99-ipv6_net.conf
    content: |
      # Disable IPv6
      net.ipv6.conf.all.disable_ipv6=1
      net.ipv6.conf.default.disable_ipv6=1
      net.ipv6.conf.lo.disable_ipv6=1

  - path: /etc/ssh/sshd_config
    content: |
      AcceptEnv LANG LC_*
      AllowUsers ebal
      ChallengeResponseAuthentication no
      Compression NO
      MaxSessions 3
      PasswordAuthentication no
      PermitRootLogin no
      Port "${sshdport}"
      PrintMotd no
      Subsystem sftp  /usr/lib/openssh/sftp-server
      UseDNS no
      UsePAM yes
      X11Forwarding no
  - path: /etc/systemd/network/eth0.network
    content: |
      [Match]
      Name=eth0

      [Network]
      Address=192.168.122.${ipadddr}/24
      Gateway=192.168.122.1

# Set TimeZone
timezone: ${timezone}

hostname: ${hostname}

growpart:
  mode: auto
  devices: ["/"]
  ignore_growroot_disabled: false

# Create swap partition
swap:
  filename: /swap.img
  size: "auto"
  maxsize: 4G

# Update/Upgrade & Reboot if necessary
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - jq
  - figlet

# PostInstall
runcmd:
  - figlet $(hostname) > /etc/motd
  # Firewall
  - ufw allow in "${sshdport}"/tcp
  - ufw allow in http/tcp

  - ufw enable
  # Remove cloud-init
  - apt-get -y autoclean
  - apt-get -y clean all
  - apt-get -y --purge autoremove cloud-init lxc lxd snapd

